### ISSUE TITLE
api: nginx content body size sometimes not large enough

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara-collection#1]
Happened to find some failures in nginx logs:
```
2020/06/25 16:15:33 [error] 3336#0: *27331 client intended to send too large body: 1631835 bytes, client: 10.168.20.167, server: ara.domain.tld, request: "POST /api/v1/results HTTP/1.1", host: "ara.domain.tld"
2020/06/25 16:15:34 [error] 3336#0: *27332 client intended to send too large body: 1565451 bytes, client: 10.168.20.167, server: ara.domain.tld, request: "POST /api/v1/results HTTP/1.1", host: "ara.domain.tld"
2020/06/25 16:23:07 [error] 3336#0: *28184 client intended to send too large body: 1698120 bytes, client: 10.168.20.167, server: ara.domain.tld, request: "POST /api/v1/results HTTP/1.1", host: "ara.domain.tld"
2020/06/25 16:23:09 [error] 3336#0: *28185 client intended to send too large body: 1641727 bytes, client: 10.168.20.167, server: ara.domain.tld, request: "POST /api/v1/results HTTP/1.1", host: "ara.domain.tld"
2020/06/25 16:23:09 [error] 3336#0: *28186 client intended to send too large body: 1549986 bytes, client: 10.168.20.167, server: ara.domain.tld, request: "POST /api/v1/results HTTP/1.1", host: "ara.domain.tld"
2020/06/26 19:40:48 [error] 3336#0: *34997 client intended to send too large body: 1072237 bytes, client: 10.168.43.105, server: ara.domain.tld, request: "POST /api/v1/results HTTP/1.1", host: "ara.domain.tld"
2020/06/26 19:40:49 [error] 3336#0: *34999 client intended to send too large body: 1124136 bytes, client: 10.168.43.105, server: ara.domain.tld, request: "POST /api/v1/results HTTP/1.1", host: "ara.domain.tld"
2020/06/26 19:40:52 [error] 3336#0: *35000 client intended to send too large body: 1149775 bytes, client: 10.168.43.105, server: ara.domain.tld, request: "POST /api/v1/results HTTP/1.1", host: "ara.domain.tld"
2020/06/26 19:49:56 [error] 3336#0: *35957 client intended to send too large body: 1481269 bytes, client: 10.168.43.105, server: ara.domain.tld, request: "POST /api/v1/results HTTP/1.1", host: "ara.domain.tld"
2020/06/26 19:50:00 [error] 3336#0: *35958 client intended to send too large body: 1477393 bytes, client: 10.168.43.105, server: ara.domain.tld, request: "POST /api/v1/results HTTP/1.1", host: "ara.domain.tld"
```

**Comment by Thulium-Drake** [comment]
I did some grepping on my logs, I have seen it only once in the past 10 months. On my system it can't be related to ```client_max_body_size``` as it's set to 2 gigs.

What would be a useful direction to look into for a solution? (or at least something to reprouce it)

**Comment by dmsimard** [comment]
@Thulium-Drake 2GB client_max_body_size is enormous :P

I think the right fix would be to add a default variable (say, ``ara_nginx_client_max_body_size: 15M``) and then add that into the template around here: https://github.com/ansible-community/ara-collection/blob/master/roles/ara_frontend_nginx/templates/ara-api.conf.j2#L11

Looking at the role, it doesn't have a ``defaults/main.yaml`` yet but there's a first time for everything.

**Comment by Thulium-Drake** [comment]
I know ;-) but it's the default that's being set by the generic reverse proxy role I use (which I also put in front of stuff like Nextcloud etc.).

Yeah, sounds like a plan, but I'm not sure if this is actually the problem. Were you able to reduce/fix the errors in the environment where this happens? That'd help with determining a sensible default.

**Comment by dmsimard** [comment]
In my experience, sometimes the output of a task is legitimately big, think like a bash script that runs for 20+ minutes with a bunch of debug and verbose output.

I'm not going to say that it's a good practice or a good idea to do that with Ansible but it's how users might end up POSTing something larger than the default.
