### ISSUE TITLE
Roles break when inject_facts_as_vars == false

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-community/ara-collection#26]
When this setting is enabled in ansible.cfg none of the ```ansible_``` variables are available, so the role breaks.

As it is unknown what the future of this option is (it is enabled now, but might be disabled by default later), we should prepare for it.

Replacing all ```ansible_thing``` with ```ansible_thing | default(ansible_facts['thing'])``` should do

**Comment by dmsimard** [comment]
This isn't an option that I have been using, good catch.

I'm not sure without looking it up, is ansible_facts always available regardless if ``inject_facts_as_vars`` is set or not ?
If ansible_facts is always there, I don't see an issue standardizing around it instead.

**Comment by Thulium-Drake** [comment]
Should be, yes, I'll make a PR when I'm done with the one I'm working on now :smile:
