### ISSUE TITLE
ara-web systemd service not working

### ISSUE THREAD

**Issue by pandvan** [ansible-community/ara-collection#29]
Once `ara-web` have been deployed using this collection, related service managed with the `systemd` unit exits as failed after few seconds.

Logs obtained with `systemd` and `journalctl` are not very informative about the issue
```
# systemctl status ara-web
● ara-web.service - ARA Records Ansible web client
   Loaded: loaded (/etc/systemd/system/ara-web.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-04-12 06:07:51 UTC; 800ms ago
  Process: 5388 ExecStart=/usr/bin/npm start --host 0.0.0.0 --port 3000 (code=exited, status=0/SUCCESS)
  Process: 5435 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=203/EXEC)
 Main PID: 5388 (code=exited, status=0/SUCCESS)

Apr 12 06:07:47 17bbcb71572b systemd[1]: Started ARA Records Ansible web client.
Apr 12 06:07:48 17bbcb71572b npm[5388]: > ara-web@1.0.0 start /root/.ara/git/ara-web
Apr 12 06:07:48 17bbcb71572b npm[5388]: > react-scripts start "0.0.0.0" "3000"
Apr 12 06:07:50 17bbcb71572b npm[5388]: ℹ ｢wds｣: Project is running at http://172.17.0.2/
Apr 12 06:07:50 17bbcb71572b npm[5388]: ℹ ｢wds｣: webpack output is served from
Apr 12 06:07:50 17bbcb71572b npm[5388]: ℹ ｢wds｣: Content not from webpack is served from /root/.ara/git/ara-web/public
Apr 12 06:07:50 17bbcb71572b npm[5388]: ℹ ｢wds｣: 404s will fallback to /
Apr 12 06:07:50 17bbcb71572b npm[5388]: Starting the development server...
Apr 12 06:07:51 17bbcb71572b systemd[1]: ara-web.service: Control process exited, code=exited, status=203/EXEC
Apr 12 06:07:51 17bbcb71572b systemd[1]: ara-web.service: Failed with result 'exit-code'
```

Trying to find what could cause this issue, I've found a related one for another React based project with  some suggestion on how to solve it.
Here's the link: [NodeJS React Systemd Service not working](https://serverfault.com/questions/1011413/nodejs-react-systemd-service-not-working).
As suggested in the accepted answer, I've tried to simply add `Environment=CI=true` inside the `[Service]` section of the systemd unit and now `ara-web` properly starts and working.

**Comment by dmsimard** [comment]
Hi @pandvan and thanks for looking into this.

Unfortunately, ara-web is [broken](https://github.com/ansible-community/ara-web/issues/29) right now and it doesn't have feature parity with the UI included in the API server so I can't recommend using it at this time.

**Comment by ccgthree** [comment]
Is there any update on this? I've had a bear of a time getting ara-web off the ground outside of a podman container (we'd rather not run a container in production). I just happened across this open issue and I'm wondering if I'm running into similar concerns.

**Comment by Thulium-Drake** [comment]
I think this can be closed as ara-web has been deprecated and removed from the collection in #65

**Comment by dmsimard** [comment]
> I think this can be closed as ara-web has been deprecated and removed from the collection in #65

Yes.

ara-web has been archived: https://github.com/ansible-community/ara-web

The project includes a built-in web interface.
ara-web was a standalone javascript interface and thus required a specific role to set it up.
