### ISSUE TITLE
Bug: Bad defaults in ara_api

### ISSUE THREAD

**Issue by misse** [ansible-community/ara-collection#31]
Hi everyone,

When installing the ara collection from ansible-galaxy like this:
``` ansible-galaxy collection install recordsansible.ara```
and using your example playbook like so:
```---
- name: Deploy ARA API and web client
  hosts: all
  gather_facts: yes
  vars:
    # ara_api
    ara_api_fqdn: ara-tst.local
    ara_api_wsgi_server: gunicorn
    ara_api_allowed_hosts:
      - ara-tst.local
    ara_api_cors_origin_whitelist:
      - "http://ara-tst.local"
    # ara_web
    ara_web_fqdn: ara-tst.local
    ara_web_frontend_server: nginx
    ara_web_api_endpoint: "http://ara-tst.local"
  roles:
    - recordsansible.ara.ara_api
    - recordsansible.ara.ara_web
```
The default installation method is source, and the default `ara_api_source:` is  "https://opendev.org/recordsansible/ara" while it should be "https://github.com/ansible-community/ara" as it is in your repository, but it needs to be a new version released on galaxy to fix it.

**Comment by Thulium-Drake** [comment]
Fixed in 0.1.0, so this can be closed :)
